### ISSUE TITLE
Seestrasse: rendering problem with window occlusion

### ISSUE THREAD

**Issue by pablo-mayrgundter** [bldrs-ai/test-models#5]
https://bldrs.ai/share/v/gh/Swiss-Property-AG/Seestrasse-Public/main/SEESTRASSE.ifc#c:119.61,50.37,73.68,16.18,11.25,5.74

<img width="862" alt="image" src="https://github.com/bldrs-ai/Share/assets/2480879/04f70676-3774-47f3-806e-342658bf046e">

**Comment by ConorStokes** [comment]
An initial investigation shows this issue appears to be related to a CSG operation that has broken due to a downstream dependency change.

Disabling relaggregates didn't fix the problem, disabling relvoids removed all the geometry in question. We believe this is because it's a CSG bug that happens during the application of the relvoids, but may not be limited to relvoids.

An initial investigation shows no major changes that should cause this to happen, although a small bug in the extraction code is possible. However, new code has been merged that is used in webifc and there are changes there to CSG, which indicates this may be where the incorrect winding issue has been brought in.

Assigning back to @nickcastel50 temporarily because this is probably better suited to him, having merged those changes.

**Comment by pablo-mayrgundter** [comment]
Fixed

https://bldrs.ai/share/v/gh/Swiss-Property-AG/Seestrasse-Public/main/SEESTRASSE.ifc#c:-27.82,18.967,3.257,-1.997,15.888,-18.955;share:

<img width="1470" alt="image" src="https://github.com/bldrs-ai/test-models/assets/2480879/7cd4152e-1b68-4b58-beb5-a4fe1b3e1754">
